# Generated by Django 4.1.1 on 2024-05-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deatils',
            table='ddetail_login',
        ),
    ]
