# Generated by Django 4.1.1 on 2024-05-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_deatils_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deatils',
            table='pers',
        ),
    ]
